development:
  dialect: "mysql"
  database: "rest_api_development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/rest_api_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/rest_api_production?parseTime=true&multiStatements=true&readTimeout=1s"}}